Repository THE-SOPT-Joint-Seminar-Danggn/Danggn-Android, pull requests merged in 2022-05, with the labels that each got.

#3 Feature/#1
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/res/drawable/ic_alarm.xml
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/ic_chat.svg
  app/src/main/res/drawable/ic_check.svg
  app/src/main/res/drawable/ic_down.svg
  app/src/main/res/drawable/ic_heart.svg
  app/src/main/res/drawable/ic_home.svg
  app/src/main/res/drawable/ic_home_bold.svg
  app/src/main/res/drawable/ic_home_chat.svg
  app/src/main/res/drawable/ic_img_close.svg
  app/src/main/res/drawable/ic_list.svg
  app/src/main/res/drawable/ic_menu.svg
  app/src/main/res/drawable/ic_mypage.svg
  app/src/main/res/drawable/ic_myplace.svg
  app/src/main/res/drawable/ic_no_check.svg
  app/src/main/res/drawable/ic_range.svg
  app/src/main/res/drawable/ic_share.svg
  app/src/main/res/drawable/ic_smile.svg
  app/src/main/res/drawable/ic_town.svg
  app/src/main/res/drawable/ic_word.svg
  app/src/main/res/font/roboto.xml
  app/src/main/res/font/roboto_bold.ttf
  app/src/main/res/font/roboto_medium.ttf
  app/src/main/res/font/roboto_regular.ttf
  app/src/main/res/font/roboto_semi_bold.ttf
  app/src/main/res/values/colors.xml
Labels: feat

#10 Feature/#7
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/seminar/presentation/read/ReadActivity.kt
  app/src/main/java/org/sopt/seminar/presentation/read/ReadImageViewPagerAdapter.kt
  app/src/main/res/drawable/ic_arrow.xml
  app/src/main/res/drawable/ic_heart_on.xml
  app/src/main/res/drawable/oval_circlegray.xml
  app/src/main/res/drawable/oval_while.xml
  app/src/main/res/drawable/profile.png
  app/src/main/res/drawable/read_state_bottom_sheet.xml
  app/src/main/res/drawable/rectangle_blue_3dp.xml
  app/src/main/res/drawable/rectangle_circlegray_3dp.xml
  app/src/main/res/drawable/rectangle_linegray_1dp.xml
  app/src/main/res/drawable/rectangle_orange2_radius4dp.xml
  app/src/main/res/drawable/rectangle_squaregray_3dp.xml
  app/src/main/res/drawable/selector_read_heart.xml
  app/src/main/res/drawable/selector_read_img_circle_indicator.xml
  app/src/main/res/layout/activity_read.xml
  app/src/main/res/layout/read_bottom_sheet.xml
  app/src/main/res/layout/read_viewpager_item.xml
  app/src/main/res/values/themes.xml
Labels: 채영, feat

#19 Feature/#16
  .idea/misc.xml
  app/src/main/java/org/sopt/seminar/presentation/write/screens/PictureAdapter.kt
  app/src/main/java/org/sopt/seminar/presentation/write/screens/WriteActivity.kt
  app/src/main/java/org/sopt/seminar/presentation/write/viewmodels/WriteViewModel.kt
Labels: 수빈, feat, refactor

#27 Feature/#20
  .idea/.name
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/org/sopt/seminar/data/api/CreateService.kt
  app/src/main/java/org/sopt/seminar/data/api/ServiceCreator.kt
  app/src/main/java/org/sopt/seminar/data/model/response/RequestCreate.kt
  app/src/main/java/org/sopt/seminar/data/model/response/ResponseCreate.kt
  app/src/main/java/org/sopt/seminar/presentation/write/screens/PictureData.kt
  app/src/main/java/org/sopt/seminar/presentation/write/screens/WriteActivity.kt
Labels: 연진, feat
